baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Tom Mason"
theme = "hugo-resume"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    firstName = "Tom"
    lastName = "Mason"
    address = "Melbourne, Australia"
    phone = "1-555-555-1234"
    contactNote = "PhD Student"
    profileImage = "img/12_apos.jpg"
    email_visible = "tom.mason14@gmail.com"
    email_target = "tom.mason14+website@gmail.com"
    # description = "PhD Student at [Monash Unversity](www.monash.edu) looking at chemistry through code." # link not parsed
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = true
    showExperience = true
    showEducation = true
    showBlog = false
    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/tom-mason-36043b101/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/tommason14/"

# [[params.handles]]
#     name = "Bitbucket"
#     link = "https://bitbucket.org/eddiewebb/"
# 
# [[params.handles]]
#     name = "Stack Overflow"
#     link = "https://stackoverflow.com/users/story/82880"
#     icon = "stack-overflow"
# 
# [[params.handles]]
#     name = "Keybase"
#     link = "https://keybase.io/edwardawebb"
#     icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
    

